theme: jekyll-theme-leap-day  
title: Elizabeth Max's Thesis
description: >
  Graduate Student at Estuary & Ocean Science Center, San Francisco State University <br>
  RIPTIDES Program - Interdisciplinary Marine and Estuarine Sciences M.S.
  
