title: Elizabeth Max's Master of Science Thesis
description: Interdisciplinary Marine and Estuarine Sciences <br>
  Estuary Ocean Science Center, San Francisco State University
theme: jekyll-theme-leap-day 
url: 'https://elizabethmax.github.io/SEFI-Intertidal-1993-2011/'
baseurl: 'SEFI-Intertidal-1993-2011'
