theme: jekyll-theme-leap-day  
title: Elizabeth Max's Thesis
description: >
  Graduate Student at Estuary & Ocean Science Center, San Francisco State University <br>
  RIPTIDES Program - Interdisciplinary Marine and Estuarine Sciences M.S. <br>
  In collaboration with Point Reyes Conservation Science, Greater Farallones National Marine Sanctuary, and <br>
  US Fish and Wildlife Farallon Islands National Wildlife Refuge
