theme: jekyll-theme-leap-day 
title: Elizabeth Max's Master of Science 2024
description: >
  Interdisciplinary Marine and Estuarine Sciences <br>
  Estuary Ocean Science Center, San Francisco State University
